// Generated by scripts/build-product-illustrations-v4.py. Do not hand-edit.
export type ProprietarySystemsProductId =
  | "ps-home"
  | "ps-ai"
  | "ps-crm"
  | "ps-prospect"
  | "ps-outreach"
  | "ps-dialer"
  | "ps-email-signatures"
  | "ps-creatives"
  | "ps-insights"
  | "ps-projects"
  | "ps-client-portal"
  | "ps-calendar"
  | "ps-messages"
  | "ps-sites"
  | "ps-automate"
  | "ps-people"
  | "ps-strategy"
  | "ps-contracts"
  | "ps-docs"
  | "ps-sheets"
  | "ps-finance"
  | "ps-territory"
  | "ps-places";

export type ProprietarySystemsProductIllustration = {
  id: ProprietarySystemsProductId;
  label: string;
  definition: string;
  productClass: "suite-home" | "suite-module" | "external-surface";
  category: string;
  technicalBoundary: string;
  defaultRoute: string;
  marketingPath: string;
  light: string;
  dark: string;
};

export type ProprietarySystemsNavigationGroup = {
  id: string;
  label: string;
  products: ProprietarySystemsProductId[];
};

export const PROPRIETARY_SYSTEMS_PRODUCT_ILLUSTRATIONS: Record<ProprietarySystemsProductId, ProprietarySystemsProductIllustration> = {
  "ps-home": {
    id: "ps-home",
    label: "PS Home",
    definition: "unified application access and business command center",
    productClass: "suite-home",
    category: "platform",
    technicalBoundary: "platform-layer",
    defaultRoute: "/",
    marketingPath: "/platform",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-home.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-home.svg",
  },
  "ps-ai": {
    id: "ps-ai",
    label: "PS.AI",
    definition: "contextual customer assistant for conversation and policy-authorized business actions, plus a separately capability-gated task and evidence view for the server-derived Proprietary Systems internal workspace; product-development execution and credentials remain in trusted Codex workflows outside the browser",
    productClass: "suite-module",
    category: "platform",
    technicalBoundary: "platform-layer",
    defaultRoute: "/ps-ai",
    marketingPath: "/products/ps-ai",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-ai.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-ai.svg",
  },
  "ps-crm": {
    id: "ps-crm",
    label: "PS CRM",
    definition: "managed external relationships",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "platform-module",
    defaultRoute: "/crm",
    marketingPath: "/products/crm",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-crm.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-crm.svg",
  },
  "ps-prospect": {
    id: "ps-prospect",
    label: "PS Prospect",
    definition: "person and company discovery",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "platform-module",
    defaultRoute: "/prospect",
    marketingPath: "/products/prospect",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-prospect.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-prospect.svg",
  },
  "ps-outreach": {
    id: "ps-outreach",
    label: "PS Outreach",
    definition: "asynchronous engagement",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "platform-module",
    defaultRoute: "/outreach",
    marketingPath: "/products/outreach",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-outreach.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-outreach.svg",
  },
  "ps-dialer": {
    id: "ps-dialer",
    label: "PS Dialer",
    definition: "live calling",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "specialized-data-plane",
    defaultRoute: "/dialer",
    marketingPath: "/products/dialer",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-dialer.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-dialer.svg",
  },
  "ps-email-signatures": {
    id: "ps-email-signatures",
    label: "PS Email Signatures",
    definition: "employee email-signature design, assignment, deployment, and campaign management",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "compatibility-web-runtime",
    defaultRoute: "/email-signatures",
    marketingPath: "/products/email-signatures",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-email-signatures.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-email-signatures.svg",
  },
  "ps-creatives": {
    id: "ps-creatives",
    label: "PS Creatives",
    definition: "visual design, creative production, and brand assets",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "platform-module",
    defaultRoute: "/creatives",
    marketingPath: "/products/creatives",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-creatives.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-creatives.svg",
  },
  "ps-insights": {
    id: "ps-insights",
    label: "PS Insights",
    definition: "cross-functional executive analytics",
    productClass: "suite-module",
    category: "marketing-sales",
    technicalBoundary: "platform-module",
    defaultRoute: "/insights",
    marketingPath: "/products/insights",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-insights.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-insights.svg",
  },
  "ps-projects": {
    id: "ps-projects",
    label: "PS Projects",
    definition: "coordinated work",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/projects",
    marketingPath: "/products/projects",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-projects.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-projects.svg",
  },
  "ps-client-portal": {
    id: "ps-client-portal",
    label: "Client Portal",
    definition: "external customer onboarding and collaboration",
    productClass: "external-surface",
    category: "operations",
    technicalBoundary: "external-guest-surface",
    defaultRoute: "https://portal.proprietarysystems.ai",
    marketingPath: "/products/client-portal",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-client-portal.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-client-portal.svg",
  },
  "ps-calendar": {
    id: "ps-calendar",
    label: "PS Calendar",
    definition: "shared scheduling and business time",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/calendar",
    marketingPath: "/products/calendar",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-calendar.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-calendar.svg",
  },
  "ps-messages": {
    id: "ps-messages",
    label: "PS Messages",
    definition: "internal and contextual business messaging",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/messages",
    marketingPath: "/products/messages",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-messages.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-messages.svg",
  },
  "ps-sites": {
    id: "ps-sites",
    label: "PS Sites",
    definition: "website publishing",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/sites",
    marketingPath: "/products/sites",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-sites.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-sites.svg",
  },
  "ps-automate": {
    id: "ps-automate",
    label: "PS Automate",
    definition: "workflow triggers and connected actions",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/automate",
    marketingPath: "/products/automate",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-automate.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-automate.svg",
  },
  "ps-people": {
    id: "ps-people",
    label: "PS People",
    definition: "internal organizational structure and people operations",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/people",
    marketingPath: "/products/people",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-people.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-people.svg",
  },
  "ps-strategy": {
    id: "ps-strategy",
    label: "PS Strategy",
    definition: "strategic planning and decision coordination",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/strategy",
    marketingPath: "/products/strategy",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-strategy.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-strategy.svg",
  },
  "ps-contracts": {
    id: "ps-contracts",
    label: "PS Contracts",
    definition: "agreement lifecycle, execution, and legal operations",
    productClass: "suite-module",
    category: "legal",
    technicalBoundary: "platform-module",
    defaultRoute: "/contracts",
    marketingPath: "/products/contracts",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-contracts.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-contracts.svg",
  },
  "ps-docs": {
    id: "ps-docs",
    label: "PS Docs",
    definition: "document authoring",
    productClass: "suite-module",
    category: "legal",
    technicalBoundary: "platform-module",
    defaultRoute: "/docs",
    marketingPath: "/products/docs",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-docs.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-docs.svg",
  },
  "ps-sheets": {
    id: "ps-sheets",
    label: "PS Spreadsheets",
    definition: "structured calculation and tabular modeling",
    productClass: "suite-module",
    category: "finance",
    technicalBoundary: "platform-module",
    defaultRoute: "/sheets",
    marketingPath: "/products/sheets",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-sheets.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-sheets.svg",
  },
  "ps-finance": {
    id: "ps-finance",
    label: "PS Finance",
    definition: "financial planning, forecasting, and performance",
    productClass: "suite-module",
    category: "finance",
    technicalBoundary: "platform-module",
    defaultRoute: "/finance",
    marketingPath: "/products/finance",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-finance.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-finance.svg",
  },
  "ps-territory": {
    id: "ps-territory",
    label: "PS Territory",
    definition: "operational geographic coverage",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "platform-module",
    defaultRoute: "/territory",
    marketingPath: "/products/territory",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-territory.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-territory.svg",
  },
  "ps-places": {
    id: "ps-places",
    label: "PS Places",
    definition: "property and location intelligence",
    productClass: "suite-module",
    category: "operations",
    technicalBoundary: "specialized-data-plane",
    defaultRoute: "/places",
    marketingPath: "/products/places",
    light: "brand-assets/svg/product-illustrations-v4/light/ps-places.svg",
    dark: "brand-assets/svg/product-illustrations-v4/dark/ps-places.svg",
  }
};

export const PROPRIETARY_SYSTEMS_PRODUCT_ALIASES = {
  "ps-portal": "ps-home",
  "peter-ai": "ps-ai",
  "peter-studio": "ps-creatives",
  "ps-signatures": "ps-email-signatures"
} as const;

export const PROPRIETARY_SYSTEMS_NAVIGATION_GROUPS = [
  {
    "id": "platform",
    "label": "Platform",
    "products": [
      "ps-home",
      "ps-ai"
    ]
  },
  {
    "id": "marketing-sales",
    "label": "Marketing & Sales",
    "products": [
      "ps-crm",
      "ps-prospect",
      "ps-outreach",
      "ps-dialer",
      "ps-email-signatures",
      "ps-creatives",
      "ps-insights"
    ]
  },
  {
    "id": "operations",
    "label": "Operations",
    "products": [
      "ps-projects",
      "ps-client-portal",
      "ps-calendar",
      "ps-messages",
      "ps-sites",
      "ps-automate",
      "ps-people",
      "ps-strategy"
    ]
  },
  {
    "id": "legal",
    "label": "Legal",
    "products": [
      "ps-contracts",
      "ps-docs"
    ]
  },
  {
    "id": "finance",
    "label": "Finance",
    "products": [
      "ps-sheets",
      "ps-finance"
    ]
  }
] as ProprietarySystemsNavigationGroup[];

export const PROPRIETARY_SYSTEMS_FEATURED_PRODUCTS = [
  "ps-home",
  "ps-ai",
  "ps-crm",
  "ps-prospect",
  "ps-outreach",
  "ps-dialer",
  "ps-projects",
  "ps-creatives",
  "ps-calendar"
] as ProprietarySystemsProductId[];
